/**
 * Copies the production decision engine and email template into the static
 * demo, so the browser simulator runs exactly the code that runs in Apps Script.
 *   node scripts/build-demo.js          write demo/core.js and demo/template.js
 *   node scripts/build-demo.js --check  fail if the demo copies are out of date (CI)
 */
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');
const banner = '// GENERATED by scripts/build-demo.js from apps-script/ — do not edit.\n';

const outputs = {
  'demo/core.js': banner + read('apps-script/Core.js'),
  'demo/template.js': banner + 'window.WELCOME_TEMPLATE = ' + JSON.stringify(read('apps-script/WelcomeEmail.html')) + ';\n',
};

const check = process.argv.includes('--check');
let stale = false;
for (const [file, content] of Object.entries(outputs)) {
  const target = path.join(root, file);
  const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
  if (current === content) continue;
  if (check) { console.error(file + ' is out of date. Run: npm run build:demo'); stale = true; }
  else { fs.writeFileSync(target, content); console.log('wrote ' + file); }
}
if (stale) process.exit(1);
if (check) console.log('demo copies are up to date');
